### ISSUE TITLE
Export area page

### ISSUE THREAD

**Issue by loveleif** [simon1573/svg2drawable.py#2]
I argue that `--export-area-page` is more useful than `--export-area-drawing` that is currently used. I suggest changing to export page or to have an option to choose.

**Comment by Overhear8805** [comment]
Correct me if I'm wrong; `--export-area-page` crops to only export the actual drawing, while `--export-area-drawing` includes the white space (if any)?

**Comment by loveleif** [comment]
No, it's the other way around.

**Comment by Overhear8805** [comment]
@peoplesbeer, please verify that commit 46b4442 added the suggested option.

**Comment by loveleif** [comment]
Nice!
